### ISSUE TITLE
Sample SVG that is bad rendered

### ISSUE THREAD

**Issue by mrmx** [xsrf/easyeda-svg-import#6] opened 2020-12-13 17:50 UTC
A three paths svg document with no curves
[bitcoin-logo.svg.zip](https://github.com/xsrf/easyeda-svg-import/files/5685075/bitcoin-logo.svg.zip)

**Comment by xsrf** [comment] 2020-12-13 19:13
Thx, I can confirm the issue. The second shape within the path, starting with `m 15.838,26.885 -3.443,0.064 -2.516,0.022` is not parsed correctly. I was assuming that coordinates without a command are always a repetition of the previous command. However, it seems this is not true for `m`/`M`ove (which makes sense). The following coordinates are actually `l`ines. This is why the shape is not closed and the third shape is offset.

![2020-12-13 20_10_45-EasyEDA - A Simple and Powerful Electronic Circuit Design Tool](https://user-images.githubusercontent.com/8081353/102021326-5cae4d80-3d7f-11eb-8afc-5c845e138fc4.png)

I've actually not really found a documentation on how these repeated commands should be parsed. I guess I'll have to look into that.

**Comment by xsrf** [comment] 2020-12-13 20:34
The issue is fixed now, it can be properly imported as outline/track.
![2020-12-13 21_18_45-EasyEDA 6 4 7 - Projects Offline mode](https://user-images.githubusercontent.com/8081353/102022941-507bbd80-3d8a-11eb-8e8a-a384bf97f868.png)

If you import it as SVG node, it won't have the inner cutouts. This is due to the design of the SVG. The cutouts orientation needs to be reversed. In case you're looking for this, see the svg attached.
[bitcoin-logo-reversed.zip](https://github.com/xsrf/easyeda-svg-import/files/5685393/bitcoin-logo-reversed.zip)

**Closed as completed by xsrf** 2020-12-13 20:34 UTC
