### ISSUE TITLE
Uncaught TypeError: svgDocument.matchAll(...)

### ISSUE THREAD

**Issue by vlrmprjct** [xsrf/easyeda-svg-import#5] opened 2020-11-24 10:13 UTC
After selecting a svg file and hit the "Import"-Button , nothing happens.
As you can see in the screenshot below I tried this with different images.

Console Error Output:
`Uncaught TypeError: svgDocument.matchAll(...) is not a function or its return value is not iterable`

![image](https://user-images.githubusercontent.com/1859497/100080193-d5d41800-2e45-11eb-8a75-0cb421a43a93.png)

**Comment by xsrf** [comment] 2020-11-24 10:49
Okay, the regex won't match any `<path ... >` tags within the svg. I should add a proper error message for that. Can you provide an example svg?

**Comment by vlrmprjct** [comment] 2020-11-24 12:49
Sure.

[dd_normalized.zip](https://github.com/xsrf/easyeda-svg-import/files/5589916/dd_normalized.zip)

**Comment by xsrf** [comment] 2020-11-24 14:43
Thank you. The image you provided consists of a lot of `<line ... >` segments which are not yet supported. But it also contains three `<path ... >` segments which import fine for me:

![2020-11-24 15_24_50-Window](https://user-images.githubusercontent.com/8081353/100106936-6b34d380-2e69-11eb-824f-3144e0df8656.png)

You can however convert the missing lines to paths using the free software [Inkscape](https://inkscape.org/). Just open the SVG with Inkscape, **select everything** (`CTRL`+`A`) and then convert outlines to paths (**Path -> Stroke to Path**; `CTRL`+`ALT`+`C`) and save it. After that, the complete image imports fine for me. I've attached the converted image.

![2020-11-24 15_34_08-Window](https://user-images.githubusercontent.com/8081353/100108404-08443c00-2e6b-11eb-82bd-c8d99fa5b586.png)

[dd_normalized_out2path.zip](https://github.com/xsrf/easyeda-svg-import/files/5590567/dd_normalized_out2path.zip)

**Comment by vlrmprjct** [comment] 2020-11-24 14:53
Ok. 
Thank you for your response.

But the point is the posted samplefile is a valid SVG and it is created with Inkscape.
So can you please provide some DOES and DONT's for SVGs for a successful import ?

Maybe the readme.md ?

**Comment by xsrf** [comment] 2020-11-24 14:59
There is a `reference.svg` in the root of the project. Also, I cannot reproduce the issue shown in your screenshot even with an empty string loaded as SVG. I guess the browser may be the issue. Are you using the desktop version of EasyEDA? I've actually not tested that yet, I use it with Chrome in the Browser. I've read that the Desktop Version ships with an older Browser version. Maybe that is the issue?

**Comment by xsrf** [comment] 2020-11-24 15:16
Okay, confirmed that. The Desktop Version of EasyEDA ships with `Chrome/69.0.3497.128` ... `String.matchAll()` requires at least `Chrome/73` which was released in march 2019. So, for now, the extension will only work in the Browser. I'll have a look if I can find some polyfills to make it also work with that old version.

**Comment by vlrmprjct** [comment] 2020-11-24 15:44
You are right.
It depends on the browser version.
I testet it in the latest Edge Browser and its working fine with the sample svg above without any changes.

**Comment by xsrf** [comment] 2020-11-24 15:56
I found some polyfills and fixed the issue with d926c84e60e1aa75819e7403c79157be11e808c7 ... Now it should also work in the Desktop Client.

**Closed as completed by xsrf** 2020-11-24 15:56 UTC
